version: "3.9"

services:
  db:
    image: mariadb:10
    container_name: db
    restart: always
    environment:
      - MARIADB_DATABASE=wordpress
      - MARIADB_PASSWORD=v%4P4SXBavtfXALA^L@x
      - MARIADB_ROOT_PASSWORD=uFqE$TzTx&pqMuege*8W
      - MARIADB_USER=admin
    volumes:
      - ./mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 384M
        reservations:
          cpus: "0.25"
          memory: 192M

  web:
    image: wordpress:php7.4
    container_name: web
    restart: always
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=v%4P4SXBavtfXALA^L@x
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_CONFIG_EXTRA=define('WP_MEMORY_LIMIT', '256M'); define('WP_CACHE', true); define('COMPRESS_SCRIPTS', true); define('COMPRESS_CSS', true);
    volumes:
      - ./html:/var/www/html
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 384M
        reservations:
          cpus: "0.25"
          memory: 192M
