version: "2"

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    environment:
      - MARIADB_DATABASE=wordpress
      - MARIADB_PASSWORD=wordpress
      - MARIADB_ROOT_PASSWORD=wordpress
      - MARIADB_USER=wordpress

  wordpress:
    image: docker.io/bitnami/wordpress:latest
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "wordpress_data:/bitnami/wordpress"
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_BLOG_NAME=Wordpress
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_ENABLE_HTTPS=yes
      - WORDPRESS_PASSWORD=cUV(TLY75Hkz3a3DTN
      - WORDPRESS_USERNAME=admin

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
