version: "3"

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    container_name: db
    restart: always
    volumes:
      - "./db_data:/bitnami/mariadb/:rw"
    environment:
      - MARIADB_DATABASE=wordpress
      - MARIADB_PASSWORD=wordpress
      - MARIADB_ROOT_PASSWORD=wordpress
      - MARIADB_USER=wordpress

  wordpress:
    image: docker.io/bitnami/wordpress:5.8.3
    container_name: web
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "./web_data:/bitnami/wordpress/:rw"
    depends_on:
      - mariadb
    environment:
      - PHP_MAX_INPUT_VARS=3000
      - WORDPRESS_AUTO_UPDATE_LEVEL=major
      - WORDPRESS_BLOG_NAME=Wordpress
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_EMAIL=afiliado_2020@hotmail.com
      - WORDPRESS_ENABLE_HTTPS=yes
      - WORDPRESS_EXTRA_WP_CONFIG_CONTENT=define( 'WP_MEMORY_LIMIT', '256M' ); define( 'WP_CACHE', true );
      - WORDPRESS_FIRST_NAME=Jose
      - WORDPRESS_LAST_NAME=Landa
      - WORDPRESS_PASSWORD=A11B22C33D
      - WORDPRESS_USERNAME=admin
